### ISSUE TITLE
expression did not evaluate constant Point tmpPoly[(int)this->PolyPoints.size()];

### ISSUE THREAD

**Issue by Karthikdjk323** [MatteoRagni/ParkAssistant#1]

**Comment by MatteoRagni** [comment]
You can substitute lines 430 to 435 with:

```
std::vector<Point> tmpPoly = this->PolyPoints;
```

but I don't think this code can be used for production purposes. It is something that I have written a long time ago when I was still trying to figuring out how to code in c++. It has a lot of mistakes (and this line is one of them) and should be rewritten from scratch.
